### ISSUE TITLE
Source maps urls syntax changed

### ISSUE THREAD

**Issue by emirotin** [resin-io/require-cs#1]
> '//@ sourceURL' and '//@ sourceMappingURL' are deprecated, please use '//# sourceURL=' and '//# sourceMappingURL=' instead.

**Comment by Page-** [comment]
Fixed in ce2d3c77953413a7496d0f6b955f13954ce564a2

**Comment by emirotin** [comment]
What the? I've updated the module. I see creates the new syntax URLs (checked the cached sources in SessionStorage). Yet I still get the same warning in the console.

**Comment by Page-** [comment]
That's the magic of require-cache :P

**Comment by emirotin** [comment]
But where does it store things? I've cleared the sessionStorage and see the
new proper sources there

**Comment by Page-** [comment]
It stores it in session storage, so if you've cleared that and still see the issue, could it be coming from code compiled by something else?

**Comment by emirotin** [comment]
I doubt. Will check again tomorrow.
